// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace MasterSample
{
	public partial class TestMaster : ILinkMaster<TestLevelMaster>
	{
		public class TestCultureInfo
		{
            public int Culture;
			public List<TestLevelMaster> Levels;
		}

		public List<TestCultureInfo> Cultures;

		public void Link(List<TestLevelMaster> levelMasters)
		{
            Dictionary<int,TestCultureInfo> culture = new Dictionary<int,TestCultureInfo>();

			 List<TestLevelMaster> myMasters = levelMasters.FindAll (x => x.TestCode == this.Code);

			foreach (TestLevelMaster m in myMasters)
			{
                if (!culture.ContainsKey(m.Culture))
				{
                    culture[m.Culture] = new TestCultureInfo();
                    culture[m.Culture].Levels = new List<TestLevelMaster>();
				}
                culture[m.Culture].Levels.Add(m);
			}

            Cultures = culture.Values.ToList();
		}
	}

}

