// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace MasterSample
{
	public partial class TestMaster
	{
		public class TestCultureInfo
		{
			public int Culture;
			public Dictionary<int,TestLevelMaster> Levels;

			public TestCultureInfo()
			{
				Levels = new Dictionary<int, TestLevelMaster>();
			}

			public override string ToString ()
			{
				string ret = "";
				foreach (var l in Levels)
				{
					ret += string.Format ("[TestCode={0},Level={1},Culture={2}]¥n", l.Value.TestCode, l.Value.Level, l.Value.Culture);
				}
				return ret;
			}
		}

		public Dictionary<int,TestCultureInfo> Cultures;

		public void Link(List<TestLevelMaster> levelMasters)
		{
			Cultures = new Dictionary<int, TestCultureInfo> ();

			 List<TestLevelMaster> myMasters = levelMasters.FindAll (x => x.TestCode == this.Code);

			foreach (TestLevelMaster m in myMasters)
			{
				if(!Cultures.ContainsKey(m.Culture))
				{
					Cultures[m.Culture] = new TestCultureInfo();
				}
				Cultures[m.Culture].Levels[m.Level] = m;
			}
		}

		public override string ToString ()
		{
			string ret = "";
			foreach (TestCultureInfo c in Cultures.Values) {
					ret += c.ToString();
			}
			return ret;
		}
	}

}

